baseURL = "https://example.edu"
languageCode = "en-us"
title = "Kishore Puthezhath"
theme = "avicenna"
googleAnalytics = ""
timeout=3000

[params]
  subtitle= "Professor (Associate)"
  interests="Paediatric Orthopaedics, Medical Education, Biomedical research "
  cv_name= ""
  blog="https//www.knotes.co.in"

[[params.affilation]]
  name = "KUHS University"
  position = "Professor (Associate)"
  contact = ""

[[params.affilation]]
  name = "knotes.co.in"
  position = "Founder"
  contact = "drkmenon@gmail.com"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/hadisinaee"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/hadisinaee"


[[params.social]]
  name = "facebook"
  icon = "facebook"
  url = "https://facebook.com/drkmenon"
  


[[params.introduction.paragraph]]
  text="""
   """
[[params.introduction.paragraph]]
  text=""" 
  """

