baseURL = "https://kishoreputhezhath.com"
languageCode = "en-us"
title = "Kishore Puthezhath"
theme = "avicenna"
googleAnalytics = ""
timeout=3000



[params]
  subtitle= "Professor (Associate)"
  interests="Paediatric Orthopaedics, Medical Education, Biomedical research "
  cv_name= ""
  blog="https://www.knotes.co.in/#posts"

[[params.affilation]]
  name = "KUHS University"
  position = "Professor (Associate)"
  contact = ""

[[params.affilation]]
  name = "knotes.co.in"
  position = "Founder"
  contact = "drkmenon@gmail.com"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/drkmenon"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/drkmenon"


[[params.social]]
  name = "facebook"
  icon = "facebook"
  url = "https://facebook.com/drkmenon"
  


[[params.introduction.paragraph]]
  text="""Kishore Puthezhath FRCS is a professor (associate) of orthopaedics 
  and consultant paediatric orthopaedic surgeon at the KUHS. 
 He leads the Paediatric Orthopaedics in a tertiary teaching 
 hospital in Kerala.
   """
[[params.introduction.paragraph]]
  text="""The contents in this domain have been moved to [knotes](https://knotes.co.in)
  """

